Cra to vite
AplinkosMinisterija/biip-zuvinimas-web pull request #31
Opened 2023-11-30 22:52 UTC by LWangllix

2023-12-01 11:36 UTC, DovMa requested changes

2023-12-01 11:36 UTC, DovMa commented on src/service-worker.ts
Manau kad sito failo su vite isvis nebereikia, vite-plugin-pwa pats kiek zinau sugeneruoja serviceWorker

2023-12-01 11:36 UTC, DovMa commented on src/serviceWorkerRegistration.ts
sito manau taip pat nebereikia.

2023-12-05 08:31 UTC, ambrazasp approved these changes

2023-12-05 08:34 UTC, merged